### ISSUE TITLE
No way to generate a string with arbitrary length

### ISSUE THREAD

**Issue by php-coder** [qala-io/datagen#15]
In my unit test I need to generate some string. I don't have any requirements to it, just some string. I didn't find a method for that, all the existing ways require me to specify a length. I'm tried the following:
```java
String expectedName = nullOr(between(1, positiveInteger()).unicode());
```
but it makes my test very slow and failing with `OutOfMemoryError`:
```java
java.lang.OutOfMemoryError: Java heap space

	at io.qala.datagen.adaptors.CommonsLang3RandomStringUtils.random(CommonsLang3RandomStringUtils.java:251)
	at io.qala.datagen.adaptors.CommonsLang3RandomStringUtils.random(CommonsLang3RandomStringUtils.java:163)
	at io.qala.datagen.adaptors.CommonsLang3RandomStringUtils.random(CommonsLang3RandomStringUtils.java:143)
	at io.qala.datagen.adaptors.CommonsLang3RandomStringUtils.random(CommonsLang3RandomStringUtils.java:69)
	at io.qala.datagen.RandomValue.unicode(RandomValue.java:103)
	at ru.mystamps.web.util.extractor.SiteParserTest.toStringShouldReturnName(SiteParserTest.java:99)
```

Could we have a method for generating a string with some random length (but not too high to still have fast tests)?

**Comment by ctapobep** [comment]
It's very hard to come up with default max value. For some cases it 100 would make sense, for others - 100K..

**Comment by ctapobep** [comment]
Closing as Won't Fix.
